### ISSUE TITLE
rebar3_hex v7 is not compatible

### ISSUE THREAD

**Issue by HoloRin** [rabbitmq/hexpm-cli#3]
rebar3_hex v7 removes the `--without-docs` flag that this tool automatically adds on publish.

From the [release notes](https://erlangforums.com/t/rebar3-hex-v7-released/891):
> We no longer support implicit publishing of docs. With v7 you must either specify a docs provider in your hex config or use the --doc-dir switch on the publish provider in the case you use a documentation tool for which there is no provider. This also means we no longer support the doc attribute in .app.src.

So it seems to me that we can just remove the automatic addition of the flag

**Comment by lukebakken** [comment]
Fixed by #4 

@pjk25 notice this failure -

https://hush-house.pivotal.io/teams/rabbitmq-core-eng/pipelines/server-release_v3.9.x/jobs/publish-final-rabbitmq-common-to-hexpm/builds/2
